### ISSUE TITLE
bug in handling conditional rules?

### ISSUE THREAD

**Issue by smartb-pair** [terraform-providers/terraform-provider-circonus#8] opened 2017-07-26 15:27 UTC
`apply`ing a Terraform definition like this: https://gist.github.com/smartb-pair/4321e9d16ad1740085f0fa065e3d64a6 seems to break with errors about our conditionals (have also added error output in the gist comments).

**Comment by sean-** [comment] 2017-07-27 04:46
Well, huh.  Change `circonus_check.api_patterns_response_code.metric[0].type` to `numeric` and then `circonus_rule_set.api_patterns_response_code_rule.if[0].value`'s predicate to be `max_value` instead of `not_match` and use something like `299` (read: "If the value is present and higher than 299, trigger a ...")... it will work as expected.  The documentation indicates that the `http` check type's `code` parameter is supposed to be of type `text`, but it appears that it is a `numeric` type now.  This feels like an API bug, @smartb-pair .  Let me do some more digging, but the suggestion to use `numeric` seems to work atm.

```
resource "circonus_check" "api_patterns_response_code" {
  name = "Authed pattern response"
  period = "60s"

  collector {
    id = "/broker/1"
  }

  metric {
    name = "code"
    type = "numeric"
  }

  http {
      url = "https://example.com"

  }
}

resource "circonus_rule_set" "api_patterns_response_code_rule" {
  check       = "${circonus_check.api_patterns_response_code.checks[0]}"
  metric_name = "code"

  if {
    value {
      max_value = "299"
    }

    then {
      notify = [ "/contact_group/2378" ] ## 'Incidents' group in Circonus
      severity = 1
    }
  }

  if {
    value {
      absent = "120s"
    }

    then {
      notify = [ "/contact_group/2378" ] ## 'Incidents' group in Circonus
      severity = 1
    }
  }
}
```

**Comment by smartb-pair** [comment] 2017-07-27 15:33
Not sure if it's related, but it looks to me like the relationship between a check and a ruleset isn't preserved if `max_value` is changed (this leads to false-positive alert conditions):
```
~ circonus_rule_set.api_patterns_route_response
    if.0.value.2206231508.absent:      "" => ""
    if.0.value.2206231508.changed:     "" => ""
    if.0.value.2206231508.contains:    "" => ""
    if.0.value.2206231508.match:       "" => ""
    if.0.value.2206231508.max_value:   "" => "200"
    if.0.value.2206231508.min_value:   "" => ""
    if.0.value.2206231508.not_contain: "" => ""
    if.0.value.2206231508.not_match:   "" => ""
    if.0.value.2206231508.over.#:      "0" => "0"
    if.0.value.538330008.absent:       "" => ""

    if.0.value.538330008.changed:      "false" => "false"
    if.0.value.538330008.contains:     "" => ""
    if.0.value.538330008.match:        "" => ""
    if.0.value.538330008.max_value:    "201" => ""
    if.0.value.538330008.min_value:    "" => ""
    if.0.value.538330008.not_contain:  "" => ""
    if.0.value.538330008.not_match:    "" => ""
    if.0.value.538330008.over.#:       "0" => "0"
```

**Comment by sean-** [comment] 2017-07-27 15:41
@smartb-pair What's your `.tf` for the ruleset?  And does the plan converge (i.e. if you run `terraform plan && terraform apply` twice, you should see no drift between them).

**Comment by smartb-pair** [comment] 2017-07-27 15:44
It's the same .tf you recommended, essentially. I'll be on Slack
momentarily I hope so we can hash it out.

**Comment by smartb-pair** [comment] 2017-07-27 15:46
I ended up just tainting and re-creating both resources since today has been pretty full and I don't have time to do a lot of debug cycles unfortunately.

**Comment by maier** [comment] 2018-03-30 13:40
@smartb-pair actually, the http check code should be treated as "text" not numeric. Internally, because it comes as text, it is treated as text which is why it will not match numeric based rules and result in alerts being generated. Here is a [circonus_check.tf](https://gist.github.com/maier/6cacd2fcef6e997c70478edf725d10db), based on your original, that i've run here as a test and it works as expected.

**Comment by sean-** [comment] 2018-09-29 13:14
@maier I am going to close this issue out.  It looks like there would be a good feature request to add improved error messages so that if a ruleset is being evaluated against an incompatible type, the API should return an error message indicating the problem is with an incompatible metric types vs ruleset predicates.  I'll admit, having a `code` be a text metric and not a numeric metric was something that I've also run into, too.  Being able to say `code <= 300` is pretty natural in every programming language when dealing with HTTP, so this POLA violation is likely to be common.

CC @kamelkev

**Closed by sean-** 2018-09-29 13:14 UTC
Labels: bug
